### ISSUE TITLE
Additional characters occurring after Group 2, Type 3 tag

### ISSUE THREAD

**Issue by Waikuteru** [Nintendo-EPD/msbt#7]
Basically either if you open or close an msbt, NX Editor currently adds weird characters after a <2> (Variable control node): 

```Enemy_AirOctarock: |-
  Kill - <0 Type='3' Data='0000'/>x췍Sky Octorok
Enemy_Assassin_Junior: |-
  <2 Type='1' Data='3c00520061006e0064006f006d0069007a00650072005f0047006f0061006c004d006f00640065005f0047006f0061006c005300740061007400750073ffff00cd'/>췍 Kill - <3 Type='2' Data='0e000200020055005000520061006e0064006f006d0069007a00650072005f00520047005f004b0069006c006c005f0045006e0065006d0079005f0041007300730061007300730069006e005f004a0075006e0069006f0072ffff00cd20005900690067006100200046006f006f00740073006f006c0064'/>椀攀爀
Enemy_Assassin_Middle: |-
  Kill - <0 Type='3' Data='0000'/>x<2 Type='2' Data='5000520061006e0064006f006d0069007a00650072005f00520047005f004b0069006c006c005f0045006e0065006d0079005f0041007300730061007300730069006e005f004d006900640064006c0065ffff00cd'/>췍⃍夀椀最愀 䈀氀愀搀攀洀愀猀琀攀爀
```

**Comment by ArchLeaders** [comment]
## Source Example:

```yml
Enemy_AirOctarock: |-
  Kill - <0 Type='3' Data='0000'/>x<2 Type='2' Data='4800520061006e0064006f006d0069007a00650072005f00520047005f004b0069006c006c005f0045006e0065006d0079005f004100690072004f0063007400610072006f0063006bffff00cd'/> Sky Octorok
Enemy_Assassin_Junior: |-
  <2 Type='1' Data='3c00520061006e0064006f006d0069007a00650072005f0047006f0061006c004d006f00640065005f0047006f0061006c005300740061007400750073ffff00cd'/> Yiga Footsoldier
Enemy_Assassin_Middle: |-
  Kill - <0 Type='3' Data='0000'/>x<2 Type='2' Data='5000520061006e0064006f006d0069007a00650072005f00520047005f004b0069006c006c005f0045006e0065006d0079005f0041007300730061007300730069006e005f004d006900640064006c0065ffff00cd'/> Yiga Blademaster
```

## Corrupt Example:

```yml
Enemy_AirOctarock: |-
  Kill - <0 Type='3' Data='0000'/>x<2 Type='2' Data='4800520061006e0064006f006d0069007a00650072005f00520047005f004b0069006c006c005f0045006e0065006d0079005f004100690072004f0063007400610072006f0063006bffff00cd'/>췍 Sky Octorok
Enemy_Assassin_Junior: |-
  <2 Type='1' Data='3c00520061006e0064006f006d0069007a00650072005f0047006f0061006c004d006f00640065005f0047006f0061006c005300740061007400750073ffff00cd'/>⃍䬀椀氀氀 ⴀ ฀̀Ȁ砀฀ȀȀ唀倀刀愀渀搀漀洀椀稀攀爀开刀䜀开䬀椀氀氀开䔀渀攀洀礀开䄀猀猀愀猀猀椀渀开䨀甀渀椀漀爀￿촀 Yiga Footsoldier
Enemy_Assassin_Middle: |-
  Kill - <0 Type='3' Data='0000'/>x<2 Type='2' Data='5000520061006e0064006f006d0069007a00650072005f00520047005f004b0069006c006c005f0045006e0065006d0079005f0041007300730061007300730069006e005f004d006900640064006c0065ffff00cd'/>췍 Yiga Blademaster
```
